# import libraries


In [1]:
import numpy as np
import pandas as pd

# import the csv file


In [3]:
df=pd.read_csv("/home/ksiva/Downloads/USA_Housing.csv")
df

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0         79545.458574             5.682861                   7.009188   
1         79248.642455             6.002900                   6.730821   
2         61287.067179             5.865890                   8.512727   
3         63345.240046             7.188236                   5.586729   
4         59982.197226             5.040555                   7.839388   
...                ...                  ...                        ...   
4995      60567.944140             7.830362                   6.137356   
4996      78491.275435             6.999135                   6.576763   
4997      63390.686886             7.250591                   4.805081   
4998      68001.331235             5.534388                   7.130144   
4999      65510.581804             5.992305                   6.792336   

      Avg. Area Number of Bedrooms  Area Population         Price  \
0                             4.09     23086.800503  1.059034e+06   
1                             3.09     40173.072174  1.505891e+06   
2                             5.13     36882.159400  1.058988e+06   
3                             3.26     34310.242831  1.260617e+06   
4                             4.23     26354.109472  6.309435e+05   
...                            ...              ...           ...   
4995                          3.46     22837.361035  1.060194e+06   
4996                          4.02     25616.115489  1.482618e+06   
4997                          2.13     33266.145490  1.030730e+06   
4998                          5.44     42625.620156  1.198657e+06   
4999                          4.07     46501.283803  1.298950e+06   

                                                Address  
0     208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1     188 Johnson Views Suite 079\nLake Kathleen, CA...  
2     9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                             USS Barnett\nFPO AP 44820  
4                            USNS Raymond\nFPO AE 09386  
...                                                 ...  
4995                   USNS Williams\nFPO AP 30153-7653  
4996              PSC 9258, Box 8489\nAPO AA 42991-3352  
4997  4215 Tracy Garden Suite 076\nJoshualand, VA 01...  
4998                          USS Wallace\nFPO AE 73316  
4999  37778 George Ridges Apt. 509\nEast Holly, NV 2...  

[5000 rows x 7 columns]

# we have to check the table data

In [4]:
df.shape

(5000, 7)

In [5]:
df.size

35000

In [7]:
df.describe()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
count       5000.000000          5000.000000                5000.000000   
mean       68583.108984             5.977222                   6.987792   
std        10657.991214             0.991456                   1.005833   
min        17796.631190             2.644304                   3.236194   
25%        61480.562388             5.322283                   6.299250   
50%        68804.286404             5.970429                   7.002902   
75%        75783.338666             6.650808                   7.665871   
max       107701.748378             9.519088                  10.759588   

       Avg. Area Number of Bedrooms  Area Population         Price  
count                   5000.000000      5000.000000  5.000000e+03  
mean                       3.981330     36163.516039  1.232073e+06  
std                        1.234137      9925.650114  3.531176e+05  
min                        2.000000       172.610686  1.593866e+04  
25%                        3.140000     29403.928702  9.975771e+05  
50%                        4.050000     36199.406689  1.232669e+06  
75%                        4.490000     42861.290769  1.471210e+06  
max                        6.500000     69621.713378  2.469066e+06

In [8]:
df.isnull().sum()

Avg. Area Income                0
Avg. Area House Age             0
Avg. Area Number of Rooms       0
Avg. Area Number of Bedrooms    0
Area Population                 0
Price                           0
Address                         0
dtype: int64

In [12]:
df.duplicated().sum()

0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
 6   Address                       5000 non-null   object 
dtypes: float64(6), object(1)
memory usage: 273.6+ KB


In [17]:
df.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  \
0                          4.09     23086.800503  1.059034e+06   
1                          3.09     40173.072174  1.505891e+06   
2                          5.13     36882.159400  1.058988e+06   
3                          3.26     34310.242831  1.260617e+06   
4                          4.23     26354.109472  6.309435e+05   

                                             Address  
0  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1  188 Johnson Views Suite 079\nLake Kathleen, CA...  
2  9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                          USS Barnett\nFPO AP 44820  
4                         USNS Raymond\nFPO AE 09386

In [18]:
df.columns

Index(['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population', 'Price', 'Address'],
      dtype='object')

# we have to seperate the dependent and indipendent columns

In [23]:
X=df[['Avg. Area Income','Avg. Area House Age','Avg. Area Number of Rooms','Avg. Area Number of Bedrooms']]
Y=df['Price'].values

In [26]:
X.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  
0                          4.09  
1                          3.09  
2                          5.13  
3                          3.26  
4                          4.23

In [28]:
Y

array([1059033.55787012, 1505890.91484695, 1058987.98787608, ...,
       1030729.58315229, 1198656.87240769, 1298950.48026696])

In [29]:
y=np.mean(Y)
y

1232072.654142357

# perform training and testing the data

# we have to import the libraries


In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.30,random_state = 0)

In [32]:
X_train

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
2858      77947.464364             6.441789                   7.193404   
1559      69931.401100             6.099507                   5.178628   
1441      65841.308786             5.587065                   6.490282   
2179      73682.486209             4.611184                   5.347027   
1390      72813.801687             8.543764                   8.204047   
...                ...                  ...                        ...   
4931      77622.958116             6.738014                   6.043040   
3264      80051.847123             5.872678                   6.019018   
1653      67094.197072             5.346437                   7.374607   
2607      52541.319847             4.885243                   7.225522   
2732      86762.882864             6.530193                   5.106962   

      Avg. Area Number of Bedrooms  
2858                          5.46  
1559                          2.28  
1441                          2.07  
2179                          2.22  
1390                          3.42  
...                            ...  
4931                          3.34  
3264                          3.39  
1653                          4.18  
2607                          3.20  
2732                          2.09  

[3500 rows x 4 columns]

In [33]:
X_test

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
398       61200.726175             5.299694                   6.234615   
3833      63380.814670             5.344664                   6.001574   
4836      71208.269301             5.300326                   6.077989   
4572      50343.763518             6.027468                   5.160240   
636       54535.453719             5.278065                   6.871038   
...                ...                  ...                        ...   
4554      75654.777016             7.077079                   6.501047   
4807      81742.851389             5.796218                   7.222546   
1073      63324.581619             7.725266                   6.213021   
2906      54673.521184             4.496193                   7.081934   
1357      40185.733891             5.949763                   5.753579   

      Avg. Area Number of Bedrooms  
398                           4.23  
3833                          2.45  
4836                          4.01  
4572                          4.35  
636                           4.41  
...                            ...  
4554                          3.15  
4807                          6.18  
1073                          4.42  
2906                          5.31  
1357                          4.01  

[1500 rows x 4 columns]

In [34]:
Y_train

array([1539129.36381118, 1389287.47386999, 1029861.62290085, ...,
       1202992.88412315,  842985.85285497, 1571253.53147505])

In [35]:
Y_test

array([ 894251.06863578,  932979.36062132,  920747.91128789, ...,
       1372994.2901085 ,  770770.58487572,  529282.08439209])

# we have to apply the algorithm

In [36]:
from sklearn.linear_model import LinearRegression

In [43]:
lr=LinearRegression()

# we have to train the dataset

In [44]:
lr.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [45]:
x=np.mean(X)
x

Avg. Area Income                68583.108984
Avg. Area House Age                 5.977222
Avg. Area Number of Rooms           6.987792
Avg. Area Number of Bedrooms        3.981330
dtype: float64

# find the coefficient and intercept

In [47]:
lr.coef_

array([ 2.14642757e+01,  1.63330109e+05,  1.23411867e+05, -2.23585958e+03])

In [48]:
lr.intercept_

-2069487.8376447964

# predict the data

In [50]:
y_pred=lr.predict(X_test)
y_pred

array([ 869708.77202385,  899067.64441117, 1065779.07966247, ...,
       1308374.89441455,  700525.71805754,  465939.41802034])

# root mean square error

In [52]:
from sklearn.metrics import mean_squared_error
lr.score(X_train,Y_train)
lr.score(X_test,Y_test)

0.7378148408015305

# r2 square

In [53]:
from sklearn.metrics import r2_score
r2_score(Y_test,y_pred)

0.7378148408015305

# r2_square using python manually

In [55]:
def get_r2_numpy():
    slope, intercept = np.polyfit(Y_test, y_pred, 1)
    r_squared = 1 - (sum((y_pred - (slope * Y_test + intercept)) ** 2) / ((len(y_pred) - 1) * np.var(y_pred, ddof=1)))
    print(r_squared)
get_r2_numpy()

0.7379389787828667
